module.exports = [
    {
        id: "1",
        item_name: "Income",
        amount: 10000.00,
        date: "2023/09/01",
        from: "Employer",
        category : "Finances",
    },
    {
        id: "2",
        item_name: "Taxes",
        amount: - 3000.00,
        date: "2023/09/01",
        from: "State & Government",
        category : "Finances",
    },
    {
        id: "3",
        item_name: "Retirement",
        amount: - 1000.00,
        date: "2023/09/01",
        from: "401k Plan",
        category : "Finances",
    },
    {
        id: "4",
        item_name: "Savings",
        amount: - 1000.00,        
        date: "2023/09/01",
        from: "Bank Account",
        category : "Finances",
    },
    {
        id: "5",
        item_name: "Credit Card Payment",
        amount: - 1000.00,
        date: "2023/09/01",
        from: "Mastercard",
        category : "Finances",
    },
    {
        id: "6",
        item_name: "Rent",
        amount: - 1500.00,
        date: "2023/09/01",
        from: "",
        category : "Residence",
    },
    {
        id: "7",
        item_name: "Mall Shopping",
        amount: - 800.00,
        date: "2023/09/03",
        from: "",
        category : "Entertainment",
    },
    {
        id: "8",
        item_name: "Groceries",
        amount: -100.00,
        date: "2023/09/06",
        from: "Market",
        category : "Food & Grocery",
    },
    {
        id: "9",
        item_name: "Pet Food",
        amount: - 100.00,
        date: "2023/09/06",
        from: "Pet Store",
        category : "Food & Grocery",
    },
    {
        id: "10",
        item_name: "Investments",
        amount: -1000.00,
        date: "2023/09/10",
        from: "Investment Portfolio",
        category : "Finances",
    },
  ];